# Generated by Django 5.2.8 on 2025-11-27 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_issuereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='location',
        ),
        migrations.AddField(
            model_name='issuereport',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='category',
            field=models.CharField(blank=True, choices=[('road issue', 'Road Issue'), ('water supply', 'Water Supply'), ('electricity', 'Electricity'), ('sanitation', 'Sanitation'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='contry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='issue_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
