# Generated by Django 5.2.8 on 2025-12-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_issuereport_location_issuereport_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='reported_at',
        ),
    ]
