# Generated by Django 5.2.8 on 2025-12-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_issuereport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='issue_id',
        ),
        migrations.AddField(
            model_name='issuereport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
