# Generated by Django 5.2.8 on 2025-12-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='category',
            field=models.CharField(blank=True, choices=[('pwd', 'Road Issue / PWD'), ('water', 'Water Authority'), ('kseb', 'Electricity / KSEB'), ('police', 'Police Station'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
